### ISSUE TITLE
error in dataset_train_rgb/train.yaml

### ISSUE THREAD

**Issue by KexianShen** [bosch-ros-pkg/bstld#20]
Hi,

In the dataset_train_rgb/train.yaml:
```yaml
- boxes:
  - {label: Red, occluded: true, x_max: 509.8248937902, x_min: 504.5962414227, y_max: 268.8949346886,
    y_min: 256.5922232358}
  - {label: Green, occluded: false, x_max: 785.3562529442, x_min: 775.3746671976,
    y_max: 298.5301082859, y_min: 276.5830549694}
  - {label: Green, occluded: false, x_max: 687.9066127428, x_min: 682.6916752957,
    y_max: 309.9256324131, y_min: 297.3849495046}
  - {label: Green, occluded: false, x_max: 598.9207546893, x_min: 592.1995969779,
    y_max: 275.9025806451, y_min: 262.283392651}
  - {label: Green, occluded: false, x_max: 785.1169839057, x_min: 786.2394607942,
    y_max: 286.8550689898, y_min: 287.1045082984}
  path: ./rgb/train/2015-10-05-11-26-32_bag/108372.png
```

The last box has x_max < x_min and y_max < y_min. This is not what we expected, right?
